package org.com.cay.entity;
// Generated 2016-11-10 11:35:43 by Hibernate Tools 5.1.0.Beta1

/**
 * Project generated by hbm2java
 */
public class Project implements java.io.Serializable {

	private int proid;
	private String proname;

	public Project() {
	}

	public Project(int proid, String proname) {
		this.proid = proid;
		this.proname = proname;
	}

	public int getProid() {
		return this.proid;
	}

	public void setProid(int proid) {
		this.proid = proid;
	}

	public String getProname() {
		return this.proname;
	}

	public void setProname(String proname) {
		this.proname = proname;
	}

}
